python3  main_glue_distill.py --distill_loss kd+saliency \
							--do_lower_case \
							--do_train \
							--task_name cola \
							--teacher_path /youtu_pedestrian_detection/xiaocui/AD-KD/experiments/exp_distill_cola/teacher \
							--student_path /youtu-reid/data/berts \
							--per_gpu_batch_size 16 \
							--num_train_epochs 20 \
							--learning_rate 5e-5 \
							--alpha 0.9 \
                            --beta 0.8 \
							--temperature 1.0  