python3 main_glue_distill.py \
    --distill_loss kd_anneal+saliency \
    --do_lower_case \
    --do_train \
    --task_name mnli \
    --teacher_path $TEACHER_PATH \
    --student_path $STUDENT_PATH \
    --per_gpu_batch_size 16 \
    --num_train_epochs 10 \
    --learning_rate 4e-5 \
    --alpha 0.8 \
    --temperature 3.0 \
    --beta 0.8
