python3 main_glue_distill.py --distill_loss kd+sinkhorn \
							--do_lower_case \
							--do_train \
							--task_name rte \
							--teacher_path $TEACHER_PATH \
							--student_path $STUDENT_PATH \
							--per_gpu_batch_size 16 \
							--num_train_epochs 5 \
							--learning_rate 2e-5 \
							--alpha 0.9 \
							--temperature 3.5  \
							--beta 0.8 \
							--topk 700 \
							--seed 20